###### numpy introduction

In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3]) #creating an array

In [3]:
array

array([1, 2, 3])

In [4]:
np.array([[1,2],[3,4],[4,5]]) #creating a 2d array

array([[1, 2],
       [3, 4],
       [4, 5]])

In [5]:
np.arange(0,10) #creating an array using arange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,10,2) #creating an array using arange but with step of 2

array([0, 2, 4, 6, 8])

In [7]:
np.zeros(3) # creating a array filled with zeros

array([0., 0., 0.])

In [8]:
np.zeros((2,4)) # creating a array filled with zeros with shape 2*4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.zeros_like(array) #creating an array filled with zeros with shape same as array that we drfined above

array([0, 0, 0])

In [10]:
np.ones(3) # creating a array filled with ones

array([1., 1., 1.])

In [11]:
np.ones((3,4)) # creating a array filled with ones with shape (3*4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.ones((3,4,2))# creating a array filled with one with shape (3*4*2)

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [13]:
np.linspace(0,10,3) #generate array with 3 numbers between 0 to 4 evenly spaced

array([ 0.,  5., 10.])

In [14]:
np.eye(3)  # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.random.rand(3,4) #generating a ranodom array from uniform distribution

array([[0.19682668, 0.66820413, 0.59460251, 0.88433989],
       [0.88399176, 0.10377554, 0.90544354, 0.06701135],
       [0.52331062, 0.90695227, 0.40356783, 0.42182955]])

In [16]:
np.random.randn(2,3) # generating a random array using standard normal distribution

array([[ 0.42073071, -1.17305411,  0.10847285],
       [-1.23078902,  1.0969771 ,  0.8017981 ]])

In [19]:
np.random.randint(2) #generating a random number in between 0 and 2

0

In [22]:
np.random.randint(1,10,(2,3)) # generating a random array of size 2*3 with all the values in between 1 and 10

array([[9, 3, 1],
       [9, 4, 4]])

In [48]:
np.random.seed(42)  # setting seed to generate same random value again
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [49]:
np.random.rand(4)  # it will generate diffrent array each time because seed is in diffrent cell

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [43]:
np.random.rand(4)

array([0.30461377, 0.09767211, 0.68423303, 0.44015249])

In [56]:
rarr = np.random.randint(1,10,10)

In [57]:
rarr.shape  # it will give the shape of an array

(10,)

In [58]:
rarr

array([2, 2, 6, 7, 5, 1, 1, 3, 2, 5])

In [59]:
rarr.reshape(2,5)  # reshaping the array in 2*5 (initial shape was (10,))

array([[2, 2, 6, 7, 5],
       [1, 1, 3, 2, 5]])

In [61]:
rarr.reshape(5*5)  

ValueError: cannot reshape array of size 10 into shape (25,)

In [64]:
rarr.min() #min value in the array

1

In [65]:
rarr.max()

7

In [66]:
rarr

array([2, 2, 6, 7, 5, 1, 1, 3, 2, 5])

In [68]:
rarr.argmin()  ## min value index in array

5

In [69]:
rarr.argmax()  #max value index in array

3

In [71]:
rarr.dtype  # data type of the array

dtype('int32')

In [72]:
arr = np.arange(0,11)

In [73]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
arr[8]  # selecting the element at index 8 

8

In [77]:
arr[0:3] # seelcting an array starting from 0 to 3rd index but not including 3rd index element

array([0, 1, 2])

In [78]:
arr[:5], arr[5:]

(array([0, 1, 2, 3, 4]), array([ 5,  6,  7,  8,  9, 10]))

In [79]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [80]:
arr[:5] = 10 # broadcasting value on 0 to 5th index(exclusive) 

In [81]:
arr

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

In [82]:
arr = np.arange(0,11)

In [86]:
array_slice = arr[:5] # array slicing but in actually it is still taking reference from the arr that means
                        # if we change the value in array_slice, it will reflect in arr also

In [87]:
array_slice

array([0, 1, 2, 3, 4])

In [88]:
hex(id(arr)), hex(id(array_slice))

('0x18cb7425df0', '0x18cb6909c60')

In [89]:
array_slice[:3] = 10

In [90]:
array_slice

array([10, 10, 10,  3,  4])

In [93]:
arr  # if you see the starting 3 elements in the original array also got changed. that measn if you want to change any value
        # than you have to exlusively make a copy of the origin al array and than do the change

array([10, 10, 10,  3,  4,  5,  6,  7,  8,  9, 10])

In [121]:
hex(id(arr))

'0x18cb7425df0'

In [94]:
arr_copy = arr.copy()

In [96]:
arr_copy

array([10, 10, 10,  3,  4,  5,  6,  7,  8,  9, 10])

#### numpy indexing

In [99]:
 arr_2d = np.array([[3,4,5],[5,6,6]])  #2D array

In [100]:
arr_2d

array([[3, 4, 5],
       [5, 6, 6]])

In [105]:
arr_2d.shape  # return no of rows * no of columns  , shape of the array

(2, 3)

In [106]:
arr_2d[0]  # selecting 1st row of the 2d array

array([3, 4, 5])

In [107]:
arr_2d[1]

array([5, 6, 6])

In [108]:
arr_2d[2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [109]:
arr_2d[0][2]  # selecting 2nd element of 0th row

5

In [112]:
arr_2d[0, 2]   # same as above, selecting 2nd element in 0th row

5

In [115]:
arr_2d[:, 2]  # selecting 2nd element in row1 and row2

array([5, 6])

In [118]:
arr_2d[:, 1:]  # selecting all the elements from the row0 and row1 starting from column 1 till last column

array([[4, 5],
       [6, 6]])

In [120]:
arr_2d[arr_2d > 5]  #filtering the array

array([6, 6])

###### numpy operations

In [122]:
arr = np.arange(0,11)

In [123]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [125]:
arr + 5  # numpy add 5 in all the elements

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [126]:
arr -2 # numpy subtract 2 from all the elements 

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [128]:
arr * arr  # numpy will multiply element to element from both array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [129]:
arr - arr # numpy will subtract element to element in both array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [130]:
rarr = np.arange(0,5)

In [131]:
arr -rarr

ValueError: operands could not be broadcast together with shapes (11,) (5,) 

In [132]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [134]:
arr/ arr  # numpy replaced the number/0 (number divider by 0) with nan

<ipython-input-134-f57fffb3827d>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/ arr  # numpy replaced the number/0 with nan


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [135]:
1/0 

ZeroDivisionError: division by zero

In [136]:
1/arr

<ipython-input-136-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [138]:
np.sqrt(arr)  ## sqrt of every element in array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [139]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [141]:
np.log(arr)

<ipython-input-141-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [143]:
arr.sum() # sum of the array

55

In [145]:
arr.mean() # mean of the array

5.0

In [147]:
arr.var() # variance of the array

10.0

In [148]:
arr.std()  # std deviation of the array

3.1622776601683795

In [154]:
arr = np.arange(0,25)

In [155]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [156]:
arr = arr.reshape(5,5)

In [157]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [158]:
arr.sum(), arr.shape

(300, (5, 5))

In [161]:
arr.sum(axis=0) # perform the operation across column

array([50, 55, 60, 65, 70])

In [163]:
arr.sum(axis=1) # perform the operation across rows

array([ 10,  35,  60,  85, 110])